# Main menu
[[main]]
    name       = "Home"
    identifier = "menu.home"
    url        = "/"
    weight     = 1

[[main]]
    name       = "Book Reviews"
    identifier = "menu.book_reviews"
    url        = "/book_reviews/"
    weight     = 2
    post       = 2

#[[main]]
#    name       = "Blog"
#    identifier = "menu.blog"
#    url        = "/blog/"
#    weight     = 3
#    post       = 2

#[[main]]
#    name       = "Categories"
#    identifier = "menu.categories"
#    url        = "/categories/"
#    weight     = 4
#    post       = 3

[[main]]
    name       = "Contact"
    identifier = "menu.contact"
    url        = "/contact/"
    weight     = 15
    post       = 4

[[main]]
    name       = "About"
    identifier = "menu.about"
    url        = "/about/"
    weight     = 10
    post       = 5

[[topbar]]
    weight = 1
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/michael-hall-8a611a1/"
    pre = "<i class='fab fa-2x fa-linkedin'></i>"

[[topbar]]
    weight = 4
    name = "Instagram"
    url = "https://www.instagram.com/mjhall32/"
    pre = "<i class='fab fa-2x fa-instagram'></i>"
