# Top Bar
[[topbar]]
    weight = 1
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/michael-hall-8a611a1/"
    pre = "<i class='fab fa-2x fa-linkedin'></i>"

[[topbar]]
    weight = 4
    name = "Instagram"
    url = "https://www.instagram.com/mjhall32/"
    pre = "<i class='fab fa-2x fa-instagram'></i>"

# Global menu
#[[main]]
#    name       = "Home"
#    identifier = "menu.home"
#    url        = "/"
#    weight     = 1

[[main]]
    name       = "Book Reviews"
    identifier = "book reviews"
    url        = "/book reviews/"
    weight     = 5
    post       = 1

#[[main]]
#    name       = "Blog"
#    identifier = "menu.blog"
#    url        = "/blog/"
#    weight     = 3
#    post       = 1

#[[main]]
#    name       = "Categories"
#    identifier = "menu.categories"
#    url        = "/categories/"
#    weight     = 4
#    post       = 1

[[main]]
    name       = "Contact"
    identifier = "menu.contact"
    url        = "/contact/"
    weight     = 150
    post       = 1

[[main]]
    name       = "About"
    identifier = "menu.about"
    url        = "/about/"
    weight     = 100
    post       = 1
