# Top Bar
[[topbar]]
    weight = 1
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/michael-hall-8a611a1/"
    pre = "<i class='fab fa-2x fa-linkedin'></i>"

[[topbar]]
    weight = 5
    name = "Instagram"
    url = "https://www.instagram.com/mjhall32/"
    pre = "<i class='fab fa-2x fa-instagram'></i>"

# Global menu
#[[main]]
#    name       = "Home"
#    identifier = "menu.home"
#    pageRef    = "/"
#    weight     = 1

[[main]]
    name       = "Book Reviews"
    identifier = "menu.book-reviews"
    pageRef    = "/book-reviews"
    weight     = 5
    post       = 1

#[[main]]
#    name       = "Blog"
#    identifier = "menu.blog"
#    pageRef    = "/blog"
#    weight     = 3
#    post       = 1

#[[main]]
#    name       = "Categories"
#    identifier = "menu.categories"
#    pageRef    = "/categories"
#    weight     = 4
#    post       = 1

[[main]]
    name       = "Contact"
    identifier = "menu.contact"
    pageRef    = "/contact"
    weight     = 150
    post       = 1

[[main]]
    name       = "About"
    identifier = "menu.about"
    pageRef    = "/about"
    weight     = 100
    post       = 1
