#baseURL                = "https://mjhall3.github.io/blog/"
baseURL                = "http://localhost:1313"
#canonifyURLs           = true
defaultContentLanguage = "en"
# https://gohugo.io/quick-reference/emojis/
enableEmoji            = true
ignoreErrors           = ["error-remote-getjson", "error-missing-instagram-accesstoken"]
languageCode           = "en-us"
pluralizeListTitles    = false
timeZone               = "America/Chicago"
title                  = "Michael's Creative Corner"
theme                  = "hugo-universal-theme"

# number of words of summarized post content (default 70)
summaryLength = 70

# not pluralize title pages by default
pluralizelisttitles = false

[pagination]
    # Define the number of posts per page
    paperSize = 20

[services]
[services.disqus]
# Enable comments by entering your Disqus shortname
#Shortname = "devcows"
[services.googleAnalytics]
# Enable Google Analytics by entering your tracking code
id = ""

[params]
    viewMorePostLink = "/blog/"
    author = "Michael Hall"
    defaultKeywords = ["personal blog", "book reviews", "books"]
    defaultDescription = ""
#    mainSections = ["book-reviews", "blog"]
    mainSections = ["book-reviews"]

    default_sharing_image = "img/engineering-banner.jpg"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"

    about_us = "<p>Michael Hall is a university lecturer at Washington University in St. Louis with a PhD in Computer Engineering. He is passionate about technology, faith, reading, and fitness. Michael enjoys writing book reviews to help fellow authors promote their work and actively supports his wife’s artistic endeavors.</p>"

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    dropdown_mouse_over = false

    disabled_logo = true
    logo_text = "Michael's Creative Corner"

    contact_url = "/contact"

[permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
#    text = """<p class="hidden-sm hidden-xs">Contact us on +420 777 555 333 or hello@universal.com.</p>
#      <p class="hidden-md hidden-lg"><a href="tel:+420 777 555 333" data-animate-hover="pulse"><i class="fas fa-phone"></i></a>
#      <a href="mailto:hello@universal.com" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
#      </p>
#      """

#[[params.menu]]
#    name = "Contact"
#    url  = "/contact"
#    weight = 4

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carouselHomepage]
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more information take a look at the README.
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.recent_posts]
    enable = true
    title = "From the blog"
    subtitle = ""
    hide_summary = false

[params.footer.recent_posts]
    enable = true

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"
