#baseURL                = "https://mjhall3.github.io/blog/"
baseURL                = "http://localhost:1313"
#canonifyURLs           = true
defaultContentLanguage = "en"
# https://gohugo.io/quick-reference/emojis/
enableEmoji            = true
ignoreErrors           = ["error-remote-getjson", "error-missing-instagram-accesstoken"]
languageCode           = "en-us"
pluralizeListTitles    = false
timeZone               = "America/Chicago"
title                  = "Michael's Creative Corner"
theme                  = "hugo-universal-theme"

# number of words of summarized post content (default 70)
summaryLength = 70

# not pluralize title pages by default
pluralizelisttitles = false

[pagination]
    # Define the number of posts per page
    paperSize = 20

[services]
[services.disqus]
# Enable comments by entering your Disqus shortname
#Shortname = "devcows"
[services.googleAnalytics]
# Enable Google Analytics by entering your tracking code
id = ""

[permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"
