baseURL = 'https://mjhall3.github.io/blog/'
title = "Michael's Creative Corner"
theme = "hugo-universal-theme"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"

#style = "default"

# number of words of summarized post content (default 70)
summaryLength = 70

# not pluralize title pages by default
pluralizelisttitles = false

[pagination]
    # Define the number of posts per page
    paperSize = 10

[services]
[services.disqus]
# Enable comments by entering your Disqus shortname
#Shortname = "devcows"
[services.googleAnalytics]
# Enable Google Analytics by entering your tracking code
id = ""

[menu]

# Main menu
[[menu.main]]
    name       = "Home"
    identifier = "menu.home"
    url        = "/"
    weight     = 1

[[menu.main]]
    name       = "Categories"
    identifier = "section.categories"
    url        = "/categories/"
    weight     = 4
    post       = 1

[[menu.main]]
    name       = "Blog"
    identifier = "section.blog"
    url        = "/blog/"
    weight     = 3
    post       = 1

[[menu.main]]
    name       = "Contact"
    identifier = "section.contact"
    url        = "/contact/"
    weight     = 15
    post       = 1

[[menu.main]]
    name       = "About"
    identifier = "section.about"
    url        = "/about/"
    weight     = 10
    post       = 1

[params]
    viewMorePostLink = "/blog/"
    author = "Michael Hall"
    defaultKeywords = ["personal blog", "book reviews", "books"]

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"

    about_us = "<p>Michael Hall is a university lecturer at Washington University in St. Louis with a PhD in Computer Engineering. He is passionate about technology, faith, reading, and fitness. Michael enjoys writing book reviews to help fellow authors promote their work and actively supports his wife’s artistic endeavors.</p>"

    dropdown_mouse_over = false


[permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.recent_posts]
    enable = true
    title = "From the blog"
    subtitle = ""
    hide_summary = false

[params.footer.recent_posts]
    enable = true

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"
