#baseURL                = "https://mjhall3.github.io/blog/"
baseURL                = "http://localhost:1313"
#canonifyURLs           = true
defaultContentLanguage = "en"
# https://gohugo.io/quick-reference/emojis/
enableEmoji            = true
ignoreErrors           = ["error-remote-getjson", "error-missing-instagram-accesstoken"]
languageCode           = "en-us"
pluralizeListTitles    = false
timeZone               = "America/Chicago"
title                  = "Michael's Creative Corner"
theme                  = "hugo-universal-theme"

# number of words of summarized post content (default 70)
summaryLength = 70

# not pluralize title pages by default
pluralizelisttitles = false

[pagination]
    # Define the number of posts per page
    paperSize = 20

[services]
[services.disqus]
# Enable comments by entering your Disqus shortname
#Shortname = "devcows"
[services.googleAnalytics]
# Enable Google Analytics by entering your tracking code
id = ""

[permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
#    text = """<p class="hidden-sm hidden-xs">Contact us on +420 777 555 333 or hello@universal.com.</p>
#      <p class="hidden-md hidden-lg"><a href="tel:+420 777 555 333" data-animate-hover="pulse"><i class="fas fa-phone"></i></a>
#      <a href="mailto:hello@universal.com" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
#      </p>
#      """

#[[params.menu]]
#    name = "Contact"
#    url  = "/contact"
#    weight = 4

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carouselHomepage]
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more information take a look at the README.
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.recent_posts]
    enable = true
    title = "From the blog"
    subtitle = ""
    hide_summary = false

[params.footer.recent_posts]
    enable = true

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"
